오타수정정

diff --git a/.github/workflows/flask-test.yml b/.github/workflows/flask-test.yml
--- a/.github/workflows/flask-test.yml
+++ b/.github/workflows/flask-test.yml
@@ -1,34 +1,37 @@
 name: Docker Test
+
 on:
-    push:
-        branches:
-            - main
+  push:
+    branches:
+      - main
 
 jobs:
-    build:
-        runs-on: ubuntu-latest
+  build:
+    runs-on: ubuntu-latest
 
-        steps:
-            - name: Checkout code
-              uses: actions/checkout@v3
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-            - name: Set up Python
-              uses: actions/setup-python@v3
-              with:
-                python-version: '3.11'
-            
-            - name: Build Flask Docker image
-              run : docker image build -t myflask-test .
+      - name: Set up Python
+        uses: actions/setup-python@v3
+        with:
+          python-version: '3.11'
 
-            - name : Run Flask Docker container
-              run : docker container run -d --name myfalsk-ac -p 8001:8001 myflask-tesk
+      - name: Build Flask Docker image
+        run: docker image build -t myflask-test .
 
-            - name: Test Flask app
-              run : |
-                sleep 10
-                curl http://127.0.0.1:8001
+      - name: Run Flask Docker container
+        run: docker container run -d --name myflask-ac -p 8001:8001 myflask-test
 
-            - name: Stop and remove Docker container
-              run : |
-                docker container stop myflask-ac
-                docker container rm myflask-ac
+      - name: Wait for the container to start
+        run: sleep 10
+
+      - name: Test Flask app
+        run: |
+          curl --fail http://localhost:8001 || (echo "Flask app failed to respond" && exit 1)
+
+      - name: Stop and remove Docker container
+        run: |
+          docker container stop myflask-ac
+          docker container rm myflask-ac
